logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web: WARN
    
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
            defaultZone: http://localhost:8761/eureka/
            
            
# Disable Hystrix timeout globally (for all services)
#hystrix.command.default.execution.timeout.enabled: false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
#hystrix.command.service-a.execution.timeout.enabled: false

# Disable Hystrix timeout for a single service
#hystrix.command.<serviceName>.execution.timeout.enabled: false

# Increase the Hystrix timeout to 60s (globally)
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

# Increase the Hystrix timeout to 60s (per service)
#hystrix.command.<serviceName>.execution.isolation.thread.timeoutInMilliseconds: 60000




zuul:  
  routes:    
    startpage:
      path: /**
      url: http://localhost:8081
    hrmsApi:      
      path: /hrmsApi/**
      url: http://localhost:8080/hrmsApi/
    tmsApi:
      path: /tmsApi/**
      url: http://localhost:8080/tmsApi
